# Change these first
owner: DaveArchetype # Your GitHub organization or username, where this repository lives
repo: sliceofchatstatus # The name of this repository

sites:
  - name: Main
    url: https://www.sliceofchat.com
  - name: Mattermost
    url: https://mattermost.sliceofchat.com
  # - name: Hacker News
  #   url: https://news.ycombinator.com
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sliceofchat.com
  # baseUrl: /your-repo-name
  logoUrl: https://seeklogo.com/images/S/shrek-logo-ED7F2DD3D1-seeklogo.com.png
  name: Slice of Chat Service Status
  introTitle: "For any problems, reach out to **Emanuel**."
  introMessage: Use this to see the current status of the services provided by Slice of Chat
  navbar:
    - title: Status
      href: /
    - title: Check Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
